#!/bin/bash
# =============================================================================
# phpMyAdmin Installation Module
# Downloads and configures phpMyAdmin with Nginx integration and a
# customizable access path for improved security.
# =============================================================================

set_steps 3

PHPMYADMIN_DIR="/usr/share/phpmyadmin"
PHPMYADMIN_VERSION="5.2.2"
PHPMYADMIN_URL="https://files.phpmyadmin.net/phpMyAdmin/${PHPMYADMIN_VERSION}/phpMyAdmin-${PHPMYADMIN_VERSION}-all-languages.tar.gz"

# ─── Step 1: Detect PHP & Download phpMyAdmin ───────────────────────────────

step "Detect PHP and download phpMyAdmin"

# Detect installed PHP versions from /etc/php/
PHP_VERSIONS=()
if [ -d /etc/php ]; then
    while IFS= read -r dir; do
        ver=$(basename "$dir")
        PHP_VERSIONS+=("$ver")
    done < <(find /etc/php -mindepth 1 -maxdepth 1 -type d | sort -V)
fi

if [ ${#PHP_VERSIONS[@]} -eq 0 ]; then
    error "No PHP installation detected in /etc/php/"
    error "Please install PHP before setting up phpMyAdmin"
    return 1
elif [ ${#PHP_VERSIONS[@]} -eq 1 ]; then
    PHP_VERSION="${PHP_VERSIONS[0]}"
    info "Detected PHP version: $PHP_VERSION"
else
    # Multiple PHP versions found — let the user choose
    select_one "Multiple PHP versions detected — select one" "${PHP_VERSIONS[@]}"
    PHP_VERSION="$SELECTED_TEXT"
    info "Selected PHP version: $PHP_VERSION"
fi

# Ensure required PHP extensions are present
show_spinner "Installing required PHP extensions" apt-get install -y \
    "php${PHP_VERSION}-mbstring" \
    "php${PHP_VERSION}-zip" \
    "php${PHP_VERSION}-gd" \
    "php${PHP_VERSION}-json" \
    "php${PHP_VERSION}-curl" \
    "php${PHP_VERSION}-mysql" \
    >/dev/null 2>&1

# Download phpMyAdmin
show_spinner "Downloading phpMyAdmin $PHPMYADMIN_VERSION" bash -c "
    wget -q '$PHPMYADMIN_URL' -O /tmp/phpmyadmin.tar.gz
"

if [ $? -ne 0 ]; then
    error "Failed to download phpMyAdmin"
    return 1
fi
success "phpMyAdmin $PHPMYADMIN_VERSION downloaded"

# ─── Step 2: Extract and Configure ──────────────────────────────────────────

step "Extract and configure phpMyAdmin"

# Remove old installation if it exists
[ -d "$PHPMYADMIN_DIR" ] && rm -rf "$PHPMYADMIN_DIR"

# Extract to /usr/share/phpmyadmin
show_spinner "Extracting phpMyAdmin" bash -c "
    mkdir -p '$PHPMYADMIN_DIR' &&
    tar -xzf /tmp/phpmyadmin.tar.gz -C '$PHPMYADMIN_DIR' --strip-components=1 &&
    rm -f /tmp/phpmyadmin.tar.gz
"

if [ $? -ne 0 ]; then
    error "Failed to extract phpMyAdmin"
    return 1
fi

# Generate a random 32-character blowfish secret
BLOWFISH_SECRET=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

# Create config.inc.php
cat > "${PHPMYADMIN_DIR}/config.inc.php" <<PHPCFG
<?php
/**
 * phpMyAdmin configuration — generated by server-setup
 */

\$cfg['blowfish_secret'] = '${BLOWFISH_SECRET}';

/* Server configuration */
\$i = 0;
\$i++;

\$cfg['Servers'][\$i]['auth_type'] = 'cookie';
\$cfg['Servers'][\$i]['host']      = 'localhost';
\$cfg['Servers'][\$i]['compress']  = false;
\$cfg['Servers'][\$i]['AllowNoPassword'] = false;

/* Temporary directory */
\$cfg['TempDir'] = '/tmp/phpmyadmin';

/* Upload / Save directories */
\$cfg['UploadDir'] = '';
\$cfg['SaveDir']   = '';
PHPCFG

# Create the temp directory
mkdir -p /tmp/phpmyadmin
chown -R www-data:www-data /tmp/phpmyadmin

# Set proper ownership and permissions
chown -R www-data:www-data "$PHPMYADMIN_DIR"
find "$PHPMYADMIN_DIR" -type d -exec chmod 755 {} \;
find "$PHPMYADMIN_DIR" -type f -exec chmod 644 {} \;
chmod 640 "${PHPMYADMIN_DIR}/config.inc.php"

success "phpMyAdmin extracted and configured"

# ─── Step 3: Configure Nginx ────────────────────────────────────────────────

step "Configure Nginx integration"

input_text "Enter access path (custom path improves security)" "phpmyadmin"
ACCESS_PATH="${INPUT_VALUE#/}"   # Strip leading slash if user added one

info "phpMyAdmin will be accessible at: /<your-domain>/${ACCESS_PATH}"

NGINX_SNIPPET="/etc/nginx/snippets/phpmyadmin.conf"

cat > "$NGINX_SNIPPET" <<NGINXCFG
# =============================================================================
# phpMyAdmin Nginx Snippet — generated by server-setup
# Include this in your server block:   include snippets/phpmyadmin.conf;
# =============================================================================

location /${ACCESS_PATH} {
    alias ${PHPMYADMIN_DIR}/;
    index index.php;

    location ~ ^/${ACCESS_PATH}/(.+\\.php)\$ {
        alias ${PHPMYADMIN_DIR}/\$1;
        fastcgi_pass unix:/run/php/php${PHP_VERSION}-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$request_filename;
        include fastcgi_params;
    }

    location ~* ^/${ACCESS_PATH}/(.+\\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))\$ {
        alias ${PHPMYADMIN_DIR}/\$1;
    }
}
NGINXCFG

success "Nginx snippet created at $NGINX_SNIPPET"
info "Add 'include snippets/phpmyadmin.conf;' inside your Nginx server block"

# Test Nginx configuration if Nginx is installed
if is_installed nginx; then
    show_spinner "Testing Nginx configuration" nginx -t 2>/dev/null
    if [ $? -eq 0 ]; then
        show_spinner "Reloading Nginx" systemctl reload nginx
        success "Nginx reloaded successfully"
    else
        warning "Nginx config test failed — please review your configuration"
    fi
else
    warning "Nginx is not installed — snippet saved for later use"
fi

# ─── Summary ────────────────────────────────────────────────────────────────

divider

show_summary "phpMyAdmin" \
    "Version=$PHPMYADMIN_VERSION" \
    "PHP Version=$PHP_VERSION" \
    "Install Path=$PHPMYADMIN_DIR" \
    "Access URL=https://<your-domain>/${ACCESS_PATH}" \
    "Nginx Snippet=$NGINX_SNIPPET" \
    "Blowfish Secret=Generated (32 chars)"

log "INFO" "phpMyAdmin $PHPMYADMIN_VERSION installed at /${ACCESS_PATH} with PHP $PHP_VERSION"
